---
title: "Untitled"
author: "Clara Rehmann"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/phd/research/spatial_sweeps/simulation/")
library(plyr)
library(tidyverse)
library(data.table)
library(MASS)
library(patchwork)
library(ggiraph)
library(scales)
library(quantreg)
```

```{r process-scan}
padf <- fread('out/power_analysis_mod.txt', fill=TRUE)
padf <- data.table(padf)
columns <- colnames(padf)[6:length(padf)]
padf <- padf %>% dplyr::select(colnames(padf)[1:6])
padf <- padf %>% tidyr::separate(N_mutations, into = columns, sep=" ")
padf <- padf %>% drop_na()
padf <- mutate_all(padf, function(x) as.numeric(as.character(x)))

padfkeep <- padf

padf
```

```{r}
## line up ticks
roundUp <- function(x,m) m*ceiling(x / m)
align_tick <- function(scoef, treetick, Nw, padf){
  sims <- unique(padf[(padf$scoef == scoef & padf$Nw == Nw),]$sim)
  for (s in sims){
      tix <- padf[(padf$scoef == scoef & padf$Nw == Nw & padf$sim == s),]$tick
      padf[(padf$scoef == scoef & padf$Nw == Nw & padf$sim == s),]$tick <- roundUp(tix, treetick)
    }
  return(padf)
}

for (Nw in c(10,100,1000)){
  padf <- align_tick(0.01, 2, Nw, padf)
  padf <- align_tick(0.001, 5, Nw, padf)
  padf <- align_tick(0.0001, 10, Nw, padf)
}

fwrite(padf, 'out/power_analysis_processed.txt')
```

```{r}
padf <- fread('out/power_analysis_processed.txt')
summ_df <- padf %>% group_by(scoef, Nw, tick) %>% dplyr::summarize(area = mean(area),
                                                                        distance=mean(distance),
                                                                   frequency=mean(frequency),
                                                                   N_mutations=mean(N_mutations),
                                                                   outliers=mean(outliers),
                                                      outlier_SNPdetected=mean(outlier_SNPdetected),
                                                      windowoutliers=mean(windowoutliers),
                                                      windowoutlier_SNPdetected=mean(windowoutlier_SNPdetected),
                                                      windowoutlier_nonoutlier_SNPdetected=mean(windowoutlier_nonoutlier_SNPdetected))
```


```{r}
ggplot(summ_df %>% arrange(scoef)) + theme_bw() +
  geom_smooth(aes(x=frequency, y=area, color=scoef, group=scoef), method='loess', span=0.05) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')

```

```{r}
ggplot(summ_df[summ_df$frequency<1,] %>% arrange(-scoef)) + theme_bw() +
  geom_hline(aes(yintercept=mean(padf$outliers / padf$N_mutations))) + 
  geom_smooth(aes(x=frequency, y=outlier_SNPdetected, color=scoef, group=scoef), method='loess',span=0.05) +
  facet_grid(cols=vars(Nw), scales='free') +
  scale_color_continuous(trans='log10') +
  scale_y_continuous(limits=c(0,1))
```

```{r}
ggplot(summ_df[summ_df$frequency<1,] %>% arrange(-scoef)) + theme_bw() +
  geom_hline(aes(yintercept=mean(padf$windowoutliers / padf$N_mutations))) + 
  geom_smooth(aes(x=frequency, y=windowoutlier_SNPdetected, color=scoef, group=scoef),method='loess',span=0.05) +
  facet_grid(cols=vars(Nw), scales='free') +
  scale_color_continuous(trans='log10')+
  scale_y_continuous(limits=c(0,1))

```

```{r}
ggplot(summ_df) + theme_bw() +
  geom_smooth(aes(x=frequency, y=outliers/N_mutations, group=scoef, color=scoef), method='loess', span=0.05) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')
```

```{r}
ggplot(summ_df) + theme_bw() +
  geom_smooth(aes(x=frequency, y=windowoutliers/N_mutations, group=scoef, color=scoef), method='loess', span=0.05) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')
```

```{r}
ggplot(summ_df) + theme_bw() +
  geom_smooth(aes(x=windowoutliers/N_mutations, y=windowoutlier_SNPdetected, group=scoef, color=scoef), method='loess', span=0.05) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')
```

```{r precision-recall}
summ_df$outlierprecision <- summ_df$outlier_SNPdetected / (summ_df$outlier_SNPdetected + (summ_df$outliers / summ_df$N_mutations))
summ_df$outlierrecall <- summ_df$outlier_SNPdetected / (summ_df$outlier_SNPdetected + (1 - summ_df$outlier_SNPdetected))

ggplot(summ_df) + theme_bw() +
  geom_line(aes(x=outlierrecall, y=outlierprecision, group=scoef, color=scoef)) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')
```


```{r precision-recall}
summ_df$windowprecision <- summ_df$windowoutlier_SNPdetected / (summ_df$windowoutlier_SNPdetected + (summ_df$windowoutliers / summ_df$N_mutations))
summ_df$windowrecall <- summ_df$windowoutlier_SNPdetected / (summ_df$windowoutlier_SNPdetected + (1 - summ_df$windowoutlier_SNPdetected))

ggplot(summ_df) + theme_bw() +
  geom_line(aes(x=windowrecall, y=windowprecision, group=scoef, color=scoef)) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')
```



```{r precision-recall}
prcdf <- padf %>% group_by(scoef, Nw, frequency) %>% dplyr::summarize(N_mutations=sum(N_mutations),
                                                                   outliers=sum(outliers),
                                                                 outlierprop=sum(outliers/N_mutations),
                                                      outlier_SNPdetected=sum(outlier_SNPdetected),
                                                      windowoutliers=sum(windowoutliers),
                                                      windowoutlier_SNPdetected=sum(windowoutlier_SNPdetected),
                                                      windowoutlier_nonoutlier_SNPdetected=sum(windowoutlier_nonoutlier_SNPdetected),
                                                      nsims = n())
```


```{r}
prcdf$outlierprecision <- prcdf$outlier_SNPdetected / (prcdf$outlier_SNPdetected + prcdf$outliers)
prcdf$outlierrecall <- prcdf$outlier_SNPdetected / prcdf$nsims
ggplot(prcdf) + theme_bw() +
  geom_line(aes(x=outlierrecall, y=outlierprecision, group=scoef, color=scoef)) +
  facet_wrap(vars(Nw)) +
  scale_color_continuous(trans='log10')

```


```{r process-scan}
padf <- fread('power_analysis_sliding_cutoff.txt', fill=TRUE)
padf <- data.table(padf)
columns <- colnames(padf)[7:length(padf)]
padf <- padf %>% dplyr::select(colnames(padf)[1:9])
padf <- padf %>% tidyr::separate(frequency, into = columns, sep=" ")
padf <- padf %>% drop_na()
padf <- mutate_all(padf, function(x) as.numeric(as.character(x)))

#padfkeep <- padf

padf
```

```{r}
## line up ticks
roundUp <- function(x,m) m*ceiling(x / m)
align_tick <- function(scoef, treetick, Nw, padf){
  sims <- unique(padf[(padf$scoef == scoef & padf$Nw == Nw),]$sim)
  for (s in sims){
      tix <- padf[(padf$scoef == scoef & padf$Nw == Nw & padf$sim == s),]$tick
      padf[(padf$scoef == scoef & padf$Nw == Nw & padf$sim == s),]$tick <- roundUp(tix, treetick)
    }
  return(padf)
}

for (Nw in c(10,100,1000)){
  padf <- align_tick(0.01, 2, Nw, padf)
  padf <- align_tick(0.001, 5, Nw, padf)
  padf <- align_tick(0.0001, 10, Nw, padf)
}

#fwrite(padf, 'out/power_analysis_processed.txt')
```

```{r}
#padf <- fread('out/power_analysis_processed.txt')
summ_df <- padf %>% group_by(scoef, Nw, cutoff, tick) %>% dplyr::summarize(area = mean(area),
                                                                        distance=mean(distance),
                                                                   frequency=mean(frequency),
                                                                   N_mutations=mean(N_mutations),
                                                                   outliers=mean(outliers),
                                                      outlier_SNPdetected=mean(outlier_SNPdetected),
                                                      windowoutliers=mean(windowoutliers),
                                                      windowoutlier_SNPdetected=mean(windowoutlier_SNPdetected),
                                                      windowoutlier_nonoutlier_SNPdetected=mean(windowoutlier_nonoutlier_SNPdetected))

fwrite(summ_df, 'power_analysis_cutoff_summary_by_tick.txt')
```


```{r}
library(viridis)
library(ggnewscale)

outliersplot <- ggplot(summ_df) + theme_minimal() + 
  geom_line(aes(x = cutoff, y=outlier_SNPdetected, color=scoef, group=scoef)) +
  geom_line(aes(x = cutoff, y = outliers/N_mutations), color='gray', linetype='dashed') +
  scale_color_viridis(option='G', trans='log10', end = 0.9) +
  facet_grid(cols=vars(Nw)) +
  scale_x_reverse()

windowsplot <- ggplot(summ_df) + theme_minimal() +
  geom_line(aes(x = cutoff, y=windowoutlier_SNPdetected, color=scoef, group=scoef)) +
  geom_line(aes(x = cutoff, y = windowoutliers/N_mutations), color='gray', linetype='dashed') +
  scale_color_viridis(option='plasma', trans='log10', end=0.9) + 
  scale_y_continuous(limits=c(0,1)) +
  facet_grid(cols=vars(Nw)) +
  scale_x_reverse()

outliersplot / windowsplot

```



```{r}
ggplot(summ_df) + theme_minimal() + 
  geom_line(aes(x = cutoff, y=outlier_SNPdetected, color=scoef, group=scoef)) +
  geom_line(aes(x = cutoff, y = outliers/N_mutations, group=scoef), color='gray', linetype='dashed') +
  scale_color_viridis(option='G', trans='log10', end = 0.9) +
  new_scale_color() + 
  geom_line(aes(x = cutoff, y=windowoutlier_SNPdetected, color=scoef, group=scoef)) +
  geom_line(aes(x = cutoff, y = windowoutliers/N_mutations, group=scoef), color='gray', linetype='dashed') +
  scale_color_viridis(option='plasma', trans='log10', end=0.97) +
  facet_grid(cols=vars(Nw))#, rows=vars(scoef))

#outliersplot / windowsplot

```


# Nate's statistic

```{r}
snpdf <- fread('out/simulation_1260_frequency_area.txt')
#snpdf <- fread('./simulation/out/simulation_1260_frequency_area.txt')
snpdf <- snpdf[snpdf$area > 0,]

N = 1000
snpdf <- snpdf %>% arrange(by = freq)
bins <- rep(seq(from = 0, to=as.integer(nrow(snpdf)/ N)), each=N)[1:nrow(snpdf)]
snpdf$bin <- bins
snpdf <- snpdf %>% dplyr::group_by(bin) %>% dplyr::mutate(Q = quantile(area, probs=0.1),
                                            bin_frequency = mean(freq))
snpdf$outlier <- FALSE
snpdf[snpdf$area <= snpdf$Q,]$outlier <- TRUE

outlierhs <- hist(snpdf[snpdf$outlier == TRUE,]$position, 
                  breaks=1000)
breaks <- outlierhs$breaks[1:length(outlierhs$breaks)-1]
outlierhs <- data.frame(breaks=breaks, mids=outlierhs$mids, outlier=outlierhs$counts)
nonoutlierhs <- hist(snpdf[snpdf$outlier == FALSE,]$position, 
                     breaks=1000)
breaks <- nonoutlierhs$breaks[1:length(nonoutlierhs$breaks)-1]
nonoutlierhs <- data.frame(breaks=breaks, mids=nonoutlierhs$mids, nonoutlier=nonoutlierhs$counts)
snphist <- merge(outlierhs, nonoutlierhs)


emp_q <- sum(snphist$outlier)/sum((snphist$outlier + snphist$nonoutlier))
snphist$statistic <- ((snphist$outlier / (snphist$outlier + snphist$nonoutlier)) - emp_q) / (sqrt((emp_q * (1-emp_q))/(snphist$outlier + snphist$nonoutlier)))
cutoff <- quantile(snphist$statistic, 0.95)
snphist$outlier <- FALSE
snphist[snphist$statistic > cutoff,]$outlier <- TRUE
ggplot() + geom_point(data = snphist, aes(x=mids, y=statistic, color=outlier))
```

